language: python
python:
- '3.6'
cache: pip
script:
- pip install pipenv
- pipenv install
- pipenv run blog lint
env:
  global:
  - secure: Gwa3zz7cQb0KVz44Arvi+Ve/dTGjrSbUcPaFgfPvEvBFLlbOPrYVdzGWCei+5/amxWqby9rTvEO02pd8FEkomWW3UAnMOhKryVJyRjSyB1cKYOux3KIFLaIublf4x6o+DvvW5Jajx6mfpEX7smsZsXf2OkZLVgr3Jfs/esGZbhaxyqGEdCuXQP7OnuU7Clk5KseVuhT3vekCRbgf12ru496N2qmTENPK5UczpczFqlUfZuwEoV6CEtXbRFR7D5U+o8mqjq4vgQG+vU2xOxPR5ZBrX4cA3r28pb23DxsCkXWbGuMg29m4tjs1jjbnCIxGs1nhMBGtqIyUs2jM47DC90O+cGm5sFn83bqX0W6JJhtYWHU8U2m8dqAK0q0BTVIIrZvcAF7cxwPdaXWU5RRAuCXltClO+2OT3ChHAt6EmR/Wvm8PgAVmySv03pZPqXxxzAW4U2ZNBi5wuQE+Y1C7e71Jz46dWFmUSgLH4G7mK265L9xLyciHE424nMV+/W0vm5MM8hiKAydZT0V25VXHgOIxQH6tdrts7mzWMbOC7tMYGFHfrdjdROm4rAxn45GE+rTt+09aSxgfbELDkmJUn0iDAFRHIiF+M0B1dYBPJ/WjNR/ubdbCQMd6TCu91pMzrNBTOjJv594VWmlEQN1ojyhfThlr+w5ksGE+G4LHsWk=
deploy:
  provider: script
  script: pipenv run blog deploy
  on:
    branch: master
    repo: PyLadiesCZ/roboprojekt-blog
sudo: false
