language: python
python:
- '3.6'
cache: pip
script:
- pip install pipenv
- pipenv install
- pipenv run blog lint
env:
  global:
  - secure: YSXGpqYLt7D9MrMz87NL8axEvbN9zrYdz0XbicZriwjNsWJ5p0Jz6pPtAN9F97Ifo1eWafWW6ZMngpleuUSnrD9cUkO/oI7avcLY7oemxL2+17/XuRmvx8/J6foW672S+Ka+VgTPbOCpjNxJ6o7F0LMpkRDVQxYYqeuJaDaIA0XwYvOZwSE637lJK4kMnpgUKcWvU6lgnvSM/QNq5ar6ylX2jqcYfFayniQ1PKy3t35t6tuHUZ/kd9QCGtFZ+IF54nteXMaDCpOgyExoqGIehbY/0y34N6qD3lGYrA2K0rKZWyqVw/b+0Wm6/ZOIXWH+I2PRqt6Qrsaoo8HPuaK7aX+Tjrmd/gyUeIbpChLEKSSBDjevCWEV3O+W/7tKDoZ73Juumhnl7wIkvrylZtKQr3h+6OvUsbF6YCUNuG8589oCcBC60t53pB1VxKph4jkAuo01p459y4dKIsORPNtBgmSA5YGfedwWVRbkriT4KYpCuzaT+QJSqVtFhLMpkv9ltKTl9Rxrl2nchoGu7Uwba9g5ZBXpI58kHroj/U17J3RaDTI/+UFDQVZdHVHwgFp/7vq7rWXP9ibtkhgezXrLL4HhZlXR0mqUoG0FdI8M78N06tRcwRkas4JBczHjLZ+OOfjFytb7YL81lYShZrAUwze82mXZDboczLpqCLbyi1A=
  - secure: Gwa3zz7cQb0KVz44Arvi+Ve/dTGjrSbUcPaFgfPvEvBFLlbOPrYVdzGWCei+5/amxWqby9rTvEO02pd8FEkomWW3UAnMOhKryVJyRjSyB1cKYOux3KIFLaIublf4x6o+DvvW5Jajx6mfpEX7smsZsXf2OkZLVgr3Jfs/esGZbhaxyqGEdCuXQP7OnuU7Clk5KseVuhT3vekCRbgf12ru496N2qmTENPK5UczpczFqlUfZuwEoV6CEtXbRFR7D5U+o8mqjq4vgQG+vU2xOxPR5ZBrX4cA3r28pb23DxsCkXWbGuMg29m4tjs1jjbnCIxGs1nhMBGtqIyUs2jM47DC90O+cGm5sFn83bqX0W6JJhtYWHU8U2m8dqAK0q0BTVIIrZvcAF7cxwPdaXWU5RRAuCXltClO+2OT3ChHAt6EmR/Wvm8PgAVmySv03pZPqXxxzAW4U2ZNBi5wuQE+Y1C7e71Jz46dWFmUSgLH4G7mK265L9xLyciHE424nMV+/W0vm5MM8hiKAydZT0V25VXHgOIxQH6tdrts7mzWMbOC7tMYGFHfrdjdROm4rAxn45GE+rTt+09aSxgfbELDkmJUn0iDAFRHIiF+M0B1dYBPJ/WjNR/ubdbCQMd6TCu91pMzrNBTOjJv594VWmlEQN1ojyhfThlr+w5ksGE+G4LHsWk=
deploy:
  provider: script
  script: pipenv run blog deploy
  on:
    branch: master
    repo: PyLadiesCZ/roboprojekt-blog
sudo: false
